export const FB_LOGIN_SUCCESS = 'fb_login_success'
export const FB_LOGIN_FAIL = 'fb_login_fail'
export const LOG_OUT = 'log_out'
export const FETCH_JOBS = 'fetch_jobs'
export const LIKE_JOB = 'like_job'
export const CLEAR_LIKED_JOBS = 'clear_liked_jobs'
